addr: ":8080"
close_time: "5s"
redis:
  host: "localhost"
  port: "6379"
  exp_time: 5m
postgres:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  database: "banners"
  sslmode: "disable"
  max_open_conns: 10
auth:
  admin_token: "admin_token"
  user_token: "user_token"